### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jojostx** [Mane-Olawale/laravel-termii#16]
- PHP Version: 8.0
- Laravel Version: ^9.11
- Operating system & Version: windows 10

### Description:
Undefined method **line** when called on an instance of `ManeOlawale\Laravel\Termii\Messages\Message`

### Screenshots:
![Screenshot (29)](https://user-images.githubusercontent.com/42269899/184353708-fbc147b1-fbdb-4722-a100-20eb80a36164.png)

**Comment by Mane-Olawale** [comment]
I am just seeing this... I will attend to it properly in an hour. Thank you

**Comment by Mane-Olawale** [comment]
Your code will work fine... this error in your ID is a result of a wrong Doc block...
I am still checking it
